### ISSUE TITLE
following README in develop branch gives errors

### ISSUE THREAD

**Issue by sbromberger** [alexarchambault/ammonium#36]
everything works fine until trying to display `sc`:

```
phasebang:ammonite-shell me$ shell/target/pack/bin/ammonite
Loading Ammonite Shell...
@ load.module("com.github.alexarchambault" % "ammonite-spark_1.5_2.11.7" % "0.4.  0-SNAPSHOT")
@ @transient val Spark = new ammonite.spark.Spark
log4j:WARN No appenders could be found for logger (org.eclipse.jetty.util.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Spark: Spark = Spark(uninitialized)
@ Spark.withConf(_.setMaster("local[1]"))
@ import Spark.sc
import Spark.sc
@ sc
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/01/03 13:53:46 INFO Spark$SparkContext: Running Spark version 1.5.0
16/01/03 13:53:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/01/03 13:53:46 INFO SecurityManager: Changing view acls to: me
16/01/03 13:53:46 INFO SecurityManager: Changing modify acls to: me
16/01/03 13:53:46 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(me); users with modify permissions: Set(me)
16/01/03 13:53:47 INFO Slf4jLogger: Slf4jLogger started
16/01/03 13:53:47 INFO Remoting: Starting remoting
16/01/03 13:53:47 ERROR ActorSystemImpl: Uncaught fatal error from thread [sparkDriver-akka.remote.default-remote-dispatcher-4] shutting down ActorSystem [sparkDriver]
java.lang.VerifyError: (class: org/jboss/netty/channel/socket/nio/NioWorkerPool, method: createWorker signature: (Ljava/util/concurrent/Executor;)Lorg/jboss/netty/channel/socket/nio/AbstractNioWorker;) Wrong return type in function
    at akka.remote.transport.netty.NettyTransport.<init>(NettyTransport.scala:283)
    at akka.remote.transport.netty.NettyTransport.<init>(NettyTransport.scala:240)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
    at scala.util.Try$.apply(Try.scala:192)
    at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
    at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
    at scala.util.Success.flatMap(Try.scala:231)
    at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
    at akka.remote.EndpointManager$$anonfun$9.apply(Remoting.scala:711)
    at akka.remote.EndpointManager$$anonfun$9.apply(Remoting.scala:703)
    at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
    at scala.collection.Iterator$class.foreach(Iterator.scala:742)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
    at akka.remote.EndpointManager.akka$remote$EndpointManager$$listens(Remoting.scala:703)
    at akka.remote.EndpointManager$$anonfun$receive$2.applyOrElse(Remoting.scala:491)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
    at akka.remote.EndpointManager.aroundReceive(Remoting.scala:394)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
16/01/03 13:53:47 INFO RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
16/01/03 13:53:47 INFO RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
16/01/03 13:53:47 ERROR Remoting: Remoting system has been terminated abrubtly. Attempting to shut down transports
16/01/03 13:53:47 INFO RemoteActorRefProvider$RemotingTerminator: Remoting shut down.
16/01/03 13:53:57 ERROR Spark$SparkContext: Error initializing SparkContext.
java.util.concurrent.TimeoutException: Futures timed out after [10000 milliseconds]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
    at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
    at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
    at scala.concurrent.Await$.result(package.scala:190)
    at akka.remote.Remoting.start(Remoting.scala:179)
    at akka.remote.RemoteActorRefProvider.init(RemoteActorRefProvider.scala:184)
    at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:620)
    at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:617)
    at akka.actor.ActorSystemImpl._start(ActorSystem.scala:617)
    at akka.actor.ActorSystemImpl.start(ActorSystem.scala:634)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
    at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
    at org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:121)
    at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:53)
    at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:52)
    at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:1913)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
    at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1904)
    at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:55)
    at org.apache.spark.rpc.akka.AkkaRpcEnvFactory.create(AkkaRpcEnv.scala:253)
    at org.apache.spark.rpc.RpcEnv$.create(RpcEnv.scala:53)
    at org.apache.spark.SparkEnv$.create(SparkEnv.scala:252)
    at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:193)
    at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:276)
    at org.apache.spark.SparkContext.<init>(SparkContext.scala:441)
    at ammonite.spark.Spark$SparkContext.<init>(Spark.scala:240)
    at ammonite.spark.Spark.sc(Spark.scala:197)
    at cmd4$$user$$anonfun$1.apply(Main.scala:25)
    at cmd4$$user$$anonfun$1.apply(Main.scala:24)
    at cmd4$$user.<init>(Main.scala:26)
    at cmd4.<init>(Main.scala:30)
    at cmd4$.<init>(Main.scala:3)
    at cmd4$.<clinit>(Main.scala)
    at cmd4$Main$.$main(Main.scala:68)
    at cmd4$Main.$main(Main.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at ammonite.Interpreter$$anonfun$evaluate$1$$anonfun$apply$9.apply(Interpreter.scala:320)
    at ammonite.Interpreter$.evaluating(Interpreter.scala:286)
    at ammonite.Interpreter$$anonfun$evaluate$1.apply(Interpreter.scala:320)
    at ammonite.Interpreter$$anonfun$evaluate$1.apply(Interpreter.scala:319)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.Interpreter$$anon$5$$anonfun$flatMap$5.apply(Interpreter.scala:298)
    at ammonite.Interpreter$$anon$5$$anonfun$flatMap$5.apply(Interpreter.scala:297)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at scala.util.Either$RightProjection.flatMap(Either.scala:522)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at scala.util.Either$RightProjection.flatMap(Either.scala:522)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at scala.util.Either$RightProjection.flatMap(Either.scala:522)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at scala.util.Either$RightProjection.flatMap(Either.scala:522)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at scala.util.Either$RightProjection.flatMap(Either.scala:522)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at scala.util.Either$RightProjection.flatMap(Either.scala:522)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at scala.util.Either$RightProjection.flatMap(Either.scala:522)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.Interpreter$$anon$4$$anonfun$flatMap$4.apply(Interpreter.scala:241)
    at ammonite.Interpreter$$anon$4$$anonfun$flatMap$4.apply(Interpreter.scala:235)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.Interpreter$$anon$3$$anonfun$flatMap$3$$anonfun$apply$7.apply(Interpreter.scala:227)
    at ammonite.Interpreter$$anon$3$$anonfun$flatMap$3$$anonfun$apply$7.apply(Interpreter.scala:227)
    at ammonite.util.Capture$.withOutAndErr(Capture.scala:62)
    at ammonite.util.Capture$.apply(Capture.scala:106)
    at ammonite.Interpreter$$anon$3$$anonfun$flatMap$3.apply(Interpreter.scala:227)
    at ammonite.Interpreter$$anon$3$$anonfun$flatMap$3.apply(Interpreter.scala:226)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
    at scala.util.Either$RightProjection.flatMap(Either.scala:522)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
    at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.Interpreter$$anon$2$$anonfun$flatMap$2.apply(Interpreter.scala:200)
    at ammonite.Interpreter$$anon$2$$anonfun$flatMap$2.apply(Interpreter.scala:199)
    at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
    at ammonite.ShellAction$$anonfun$interpret$1.apply(Shell.scala:109)
    at ammonite.ShellAction$$anonfun$interpret$1.apply(Shell.scala:102)
    at ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
    at ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:41)
    at ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:40)
    at ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
    at ammonite.ShellAction$$anon$2$$anonfun$flatMap$2.apply(Shell.scala:93)
    at ammonite.ShellAction$$anon$2$$anonfun$flatMap$2.apply(Shell.scala:86)
    at ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
    at ammonite.ShellAction$$anonfun$flatMap$1$$anonfun$apply$2.apply(Shell.scala:41)
    at ammonite.ShellAction$$anonfun$flatMap$1$$anonfun$apply$2.apply(Shell.scala:41)
    at scala.util.Either$RightProjection.flatMap(Either.scala:522)
    at ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:41)
    at ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:40)
    at ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
    at ammonite.Ammonite.loop(Ammonite.scala:92)
    at ammonite.Ammonite.delayedEndpoint$ammonite$Ammonite$1(Ammonite.scala:103)
    at ammonite.Ammonite$delayedInit$body.apply(Ammonite.scala:21)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at caseapp.App$$anonfun$apply$1.apply(App.scala:25)
    at caseapp.App$$anonfun$apply$1.apply(App.scala:24)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
    at caseapp.App$class.apply(App.scala:24)
    at ammonite.Ammonite.apply(Ammonite.scala:21)
    at caseapp.AppOf.main(App.scala:62)
    at ammonite.Ammonite.main(Ammonite.scala)
16/01/03 13:53:57 INFO Spark$SparkContext: Successfully stopped SparkContext
Exception: null
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:497)
  ammonite.Interpreter$$anonfun$evaluate$1$$anonfun$apply$9.apply(Interpreter.scala:320)
  ammonite.Interpreter$.evaluating(Interpreter.scala:286)
  ammonite.Interpreter$$anonfun$evaluate$1.apply(Interpreter.scala:320)
  ammonite.Interpreter$$anonfun$evaluate$1.apply(Interpreter.scala:319)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.Interpreter$$anon$5$$anonfun$flatMap$5.apply(Interpreter.scala:298)
  ammonite.Interpreter$$anon$5$$anonfun$flatMap$5.apply(Interpreter.scala:297)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  scala.util.Either$RightProjection.flatMap(Either.scala:522)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  scala.util.Either$RightProjection.flatMap(Either.scala:522)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  scala.util.Either$RightProjection.flatMap(Either.scala:522)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  scala.util.Either$RightProjection.flatMap(Either.scala:522)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  scala.util.Either$RightProjection.flatMap(Either.scala:522)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  scala.util.Either$RightProjection.flatMap(Either.scala:522)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  scala.util.Either$RightProjection.flatMap(Either.scala:522)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.Interpreter$$anon$4$$anonfun$flatMap$4.apply(Interpreter.scala:241)
  ammonite.Interpreter$$anon$4$$anonfun$flatMap$4.apply(Interpreter.scala:235)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.Interpreter$$anon$3$$anonfun$flatMap$3$$anonfun$apply$7.apply(Interpreter.scala:227)
  ammonite.Interpreter$$anon$3$$anonfun$flatMap$3$$anonfun$apply$7.apply(Interpreter.scala:227)
  ammonite.util.Capture$.withOutAndErr(Capture.scala:62)
  ammonite.util.Capture$.apply(Capture.scala:106)
  ammonite.Interpreter$$anon$3$$anonfun$flatMap$3.apply(Interpreter.scala:227)
  ammonite.Interpreter$$anon$3$$anonfun$flatMap$3.apply(Interpreter.scala:226)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:39)
  scala.util.Either$RightProjection.flatMap(Either.scala:522)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:39)
  ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:38)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.Interpreter$$anon$2$$anonfun$flatMap$2.apply(Interpreter.scala:200)
  ammonite.Interpreter$$anon$2$$anonfun$flatMap$2.apply(Interpreter.scala:199)
  ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:52)
  ammonite.ShellAction$$anonfun$interpret$1.apply(Shell.scala:109)
  ammonite.ShellAction$$anonfun$interpret$1.apply(Shell.scala:102)
  ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
  ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:41)
  ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:40)
  ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
  ammonite.ShellAction$$anon$2$$anonfun$flatMap$2.apply(Shell.scala:93)
  ammonite.ShellAction$$anon$2$$anonfun$flatMap$2.apply(Shell.scala:86)
  ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
  ammonite.ShellAction$$anonfun$flatMap$1$$anonfun$apply$2.apply(Shell.scala:41)
  ammonite.ShellAction$$anonfun$flatMap$1$$anonfun$apply$2.apply(Shell.scala:41)
  scala.util.Either$RightProjection.flatMap(Either.scala:522)
  ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:41)
  ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:40)
  ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
  ammonite.Ammonite.loop(Ammonite.scala:92)
  ammonite.Ammonite.delayedEndpoint$ammonite$Ammonite$1(Ammonite.scala:103)
  ammonite.Ammonite$delayedInit$body.apply(Ammonite.scala:21)
  scala.Function0$class.apply$mcV$sp(Function0.scala:34)
  scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
  caseapp.App$$anonfun$apply$1.apply(App.scala:25)
  caseapp.App$$anonfun$apply$1.apply(App.scala:24)
  scala.collection.immutable.List.foreach(List.scala:381)
  scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
  scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
  caseapp.App$class.apply(App.scala:24)
  ammonite.Ammonite.apply(Ammonite.scala:21)
  caseapp.AppOf.main(App.scala:62)
  ammonite.Ammonite.main(Ammonite.scala)
```

**Comment by alexarchambault** [comment]
Yep, I just force pushed something that should be make that point work better. (Stale caches induced me in error initially...).

**Comment by sbromberger** [comment]
All fixed. Thank you very much for your prompt response!!
