### ISSUE TITLE
[Spark 2.0] java.lang.IllegalArgumentException: requirement failed: File scala-parser-combinators_2.11-1.0.4.jar was already registered with a different path 

### ISSUE THREAD

**Issue by maver1ck** [alexarchambault/ammonium#64]
I did following
1) I compiled Spark and publish to local maven repo
2) I modified build.sbt of ammonium

```
diff --git a/build.sbt b/build.sbt
index 1824339..f92340b 100644
--- a/build.sbt
+++ b/build.sbt
@@ -164,6 +164,7 @@ lazy val spark161 = sparkProject("1.6.1")
 lazy val spark162 = sparkProject("1.6.2")
 lazy val spark200preview = sparkProject("2.0.0-preview")
 lazy val spark200 = sparkProject("2.0.0")
+lazy val spark201 = sparkProject("2.0.1-SNAPSHOT")

 lazy val setup = project
   .settings(commonSettings)
@@ -175,8 +176,8 @@ lazy val setup = project
   )

 lazy val `ammonium` = project.in(file("."))
-  .aggregate(`interpreter-api`, interpreter, `shell-api`, `shell-tests`, spark200, spark200preview, spark162, spark161, spark160, spark152, spark151, spark150, spark141, spark131, spark130, spark122, spark121,
-  .dependsOn(`interpreter-api`, interpreter, `shell-api`, `shell-tests`, spark200, spark200preview, spark162, spark161, spark160, spark152, spark151, spark150, spark141, spark131, spark130, spark122, spark121,
+  .aggregate(`interpreter-api`, interpreter, `shell-api`, `shell-tests`, spark201, spark200, spark200preview, spark162, spark161, spark160, spark152, spark151, spark150, spark141, spark131, spark130, spark122,
+  .dependsOn(`interpreter-api`, interpreter, `shell-api`, `shell-tests`, spark201, spark200, spark200preview, spark162, spark161, spark160, spark152, spark151, spark150, spark141, spark131, spark130, spark122,
   .settings(commonSettings)
   .settings(noPublishSettings)
   .settings(
@@ -191,6 +192,7 @@ lazy val commonSettings = releaseSettings ++ Seq(
     "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases",
     Resolver.sonatypeRepo("releases")
   ),
+  resolvers += "Local Maven Repository" at Path.userHome.asFile.toURI.toURL + ".m2/repository",
   libraryDependencies ++= {
     if (scalaBinaryVersion.value == "2.10") Seq(
       compilerPlugin(

```

Then I have following error
java.lang.IllegalArgumentException: requirement failed: File scala-parser-combinators_2.11-1.0.4.jar was already registered with a different path

```
spark2@bhg03:~/ammonium$ ./ammonium
Loading...
@ classpath.addRepository("file:/home/spark2/.m2/repository/")
@ classpath.add("com.github.alexarchambault.ammonium" % s"spark_2.0.1-SNAPSHOT_2.11.8" % "0.4.0-SNAPSHOT")
155 new artifact(s)
155 new artifacts in macro
155 new artifacts in runtime
155 new artifacts in compile
@ @transient val Spark = new ammonite.Spark
log4j:WARN No appenders could be found for logger (org.eclipse.jetty.util.log).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Spark: Spark = Spark(uninitialized)
@ import Spark.{ sparkConf, sc, sqlContext }
import Spark.{ sparkConf, sc, sqlContext }
@ sc
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/08/18 20:09:25 INFO Spark$SparkContext: Running Spark version 2.0.1-SNAPSHOT
16/08/18 20:09:26 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/08/18 20:09:26 INFO SecurityManager: Changing view acls to: spark2
16/08/18 20:09:26 INFO SecurityManager: Changing modify acls to: spark2
16/08/18 20:09:26 INFO SecurityManager: Changing view acls groups to:
16/08/18 20:09:26 INFO SecurityManager: Changing modify acls groups to:
16/08/18 20:09:26 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(spark2); groups with view permissions: Set(); users  with modify permissions: Set(spark2); groups with modify permissions: Set()
16/08/18 20:09:26 INFO Utils: Successfully started service 'sparkDriver' on port 59707.
16/08/18 20:09:26 INFO SparkEnv: Registering MapOutputTracker
16/08/18 20:09:26 INFO SparkEnv: Registering BlockManagerMaster
16/08/18 20:09:26 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-4ac9c21d-6b2c-43bb-89ef-a1fc7add6121
16/08/18 20:09:26 INFO MemoryStore: MemoryStore started with capacity 15.7 GB
16/08/18 20:09:26 INFO SparkEnv: Registering OutputCommitCoordinator
16/08/18 20:09:26 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/08/18 20:09:26 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://188.165.13.158:4040
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/scala-xml_2.11-1.0.4.jar at spark://188.165.13.158:59707/jars/scala-xml_2.11-1.0.4.jar with timestamp 1471550966990
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/shell-api_2.11.8-0.4.0-M6.jar at spark://188.165.13.158:59707/jars/shell-api_2.11.8-0.4.0-M6.jar with timestamp 1471550966991
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/scala-compiler-2.11.8.jar at spark://188.165.13.158:59707/jars/scala-compiler-2.11.8.jar with timestamp 1471550966991
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/interpreter-api_2.11.8-0.4.0-M6.jar at spark://188.165.13.158:59707/jars/interpreter-api_2.11.8-0.4.0-M6.jar with timestamp 1471550966991
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/sourcecode_2.11-0.1.1.jar at spark://188.165.13.158:59707/jars/sourcecode_2.11-0.1.1.jar with timestamp 1471550966991
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/pprint_2.11-0.3.9.jar at spark://188.165.13.158:59707/jars/pprint_2.11-0.3.9.jar with timestamp 1471550966991
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/scala-reflect-2.11.8.jar at spark://188.165.13.158:59707/jars/scala-reflect-2.11.8.jar with timestamp 1471550966991
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/derive_2.11-0.3.9.jar at spark://188.165.13.158:59707/jars/derive_2.11-0.3.9.jar with timestamp 1471550966991
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/tprint_2.11.8-0.4.0-M6.jar at spark://188.165.13.158:59707/jars/tprint_2.11.8-0.4.0-M6.jar with timestamp 1471550966991
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/scala-library-2.11.8.jar at spark://188.165.13.158:59707/jars/scala-library-2.11.8.jar with timestamp 1471550966991
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/home/spark2/.ammonium/bootstrap/scala-parser-combinators_2.11-1.0.4.jar at spark://188.165.13.158:59707/jars/scala-parser-combinators_2.11-1.0.4.jar with timestamp 1471550966992
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/dnsns.jar at spark://188.165.13.158:59707/jars/dnsns.jar with timestamp 1471550966992
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/sunjce_provider.jar at spark://188.165.13.158:59707/jars/sunjce_provider.jar with timestamp 1471550966992
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/zipfs.jar at spark://188.165.13.158:59707/jars/zipfs.jar with timestamp 1471550966992
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/localedata.jar at spark://188.165.13.158:59707/jars/localedata.jar with timestamp 1471550966992
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/icedtea-sound.jar at spark://188.165.13.158:59707/jars/icedtea-sound.jar with timestamp 1471550966992
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/sunpkcs11.jar at spark://188.165.13.158:59707/jars/sunpkcs11.jar with timestamp 1471550966992
16/08/18 20:09:26 INFO Spark$SparkContext: Added JAR file:/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar at spark://188.165.13.158:59707/jars/java-atk-wrapper.jar with timestamp 1471550966992
16/08/18 20:09:26 ERROR Spark$SparkContext: Error initializing SparkContext.
java.lang.IllegalArgumentException: requirement failed: File scala-parser-combinators_2.11-1.0.4.jar was already registered with a different path (old path = /home/spark2/.ammonium/bootstrap/scala-parser-combinators_2.11-1.0.4.jar, new path = /home/spark2/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar
        at scala.Predef$.require(Predef.scala:224)
        at org.apache.spark.rpc.netty.NettyStreamManager.addJar(NettyStreamManager.scala:78)
        at org.apache.spark.SparkContext.liftedTree2$1(SparkContext.scala:1703)
        at org.apache.spark.SparkContext.addJar(SparkContext.scala:1702)
        at org.apache.spark.SparkContext$$anonfun$11.apply(SparkContext.scala:457)
        at org.apache.spark.SparkContext$$anonfun$11.apply(SparkContext.scala:457)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
        at ammonite.Spark$SparkContext.<init>(Spark.scala:306)
        at ammonite.Spark.sc(Spark.scala:226)
        at cmd4$$user$$anonfun$1.apply(Main.scala:25)
        at cmd4$$user$$anonfun$1.apply(Main.scala:24)
        at cmd4$$user.<init>(Main.scala:26)
        at cmd4.<init>(Main.scala:30)
        at cmd4$.<init>(Main.scala:3)
        at cmd4$.<clinit>(Main.scala)
        at cmd4$Main$.$main(Main.scala:71)
        at cmd4$Main.$main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at ammonite.Interpreter$$anonfun$evaluate$1$$anonfun$apply$9.apply(Interpreter.scala:325)
        at ammonite.Interpreter$.evaluating(Interpreter.scala:291)
        at ammonite.Interpreter$$anonfun$evaluate$1.apply(Interpreter.scala:325)
        at ammonite.Interpreter$$anonfun$evaluate$1.apply(Interpreter.scala:324)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:43)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.Interpreter$$anon$5$$anonfun$flatMap$5.apply(Interpreter.scala:303)
        at ammonite.Interpreter$$anon$5$$anonfun$flatMap$5.apply(Interpreter.scala:302)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:43)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:43)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:43)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:43)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:43)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:43)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:43)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.Interpreter$$anon$4$$anonfun$flatMap$4.apply(Interpreter.scala:246)
        at ammonite.Interpreter$$anon$4$$anonfun$flatMap$4.apply(Interpreter.scala:240)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.Interpreter$$anon$3$$anonfun$flatMap$3$$anonfun$apply$7.apply(Interpreter.scala:232)
        at ammonite.Interpreter$$anon$3$$anonfun$flatMap$3$$anonfun$apply$7.apply(Interpreter.scala:232)
        at ammonite.util.Capture$.withOutAndErr(Capture.scala:62)
        at ammonite.util.Capture$.apply(Capture.scala:106)
        at ammonite.Interpreter$$anon$3$$anonfun$flatMap$3.apply(Interpreter.scala:232)
        at ammonite.Interpreter$$anon$3$$anonfun$flatMap$3.apply(Interpreter.scala:231)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1$$anonfun$apply$3.apply(Interpreter.scala:44)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:44)
        at ammonite.InterpreterAction$$anonfun$flatMap$1.apply(Interpreter.scala:43)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.Interpreter$$anon$2$$anonfun$flatMap$2.apply(Interpreter.scala:205)
        at ammonite.Interpreter$$anon$2$$anonfun$flatMap$2.apply(Interpreter.scala:204)
        at ammonite.InterpreterAction$$anon$1.apply(Interpreter.scala:57)
        at ammonite.ShellAction$$anonfun$interpret$1.apply(Shell.scala:110)
        at ammonite.ShellAction$$anonfun$interpret$1.apply(Shell.scala:103)
        at ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
        at ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:41)
        at ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:40)
        at ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
        at ammonite.ShellAction$$anon$2$$anonfun$flatMap$2.apply(Shell.scala:94)
        at ammonite.ShellAction$$anon$2$$anonfun$flatMap$2.apply(Shell.scala:87)
        at ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
        at ammonite.ShellAction$$anonfun$flatMap$1$$anonfun$apply$2.apply(Shell.scala:41)
        at ammonite.ShellAction$$anonfun$flatMap$1$$anonfun$apply$2.apply(Shell.scala:41)
        at scala.util.Either$RightProjection.flatMap(Either.scala:522)
        at ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:41)
        at ammonite.ShellAction$$anonfun$flatMap$1.apply(Shell.scala:40)
        at ammonite.ShellAction$$anon$1.apply(Shell.scala:50)
        at ammonite.AmmoniteApp.loop(Ammonite.scala:114)
        at ammonite.AmmoniteApp.delayedEndpoint$ammonite$AmmoniteApp$1(Ammonite.scala:127)
        at ammonite.AmmoniteApp$delayedInit$body.apply(Ammonite.scala:22)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at caseapp.App$$anonfun$apply$1.apply(App.scala:47)
        at caseapp.App$$anonfun$apply$1.apply(App.scala:46)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
        at caseapp.App$class.apply(App.scala:46)
        at ammonite.AmmoniteApp.apply(Ammonite.scala:22)
        at caseapp.AppOf.main(App.scala:121)
        at ammonite.Ammonite.main(Ammonite.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at coursier.Bootstrap.main(Bootstrap.java:412)
16/08/18 20:09:27 INFO SparkUI: Stopped Spark web UI at http://188.165.13.158:4040
16/08/18 20:09:27 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
16/08/18 20:09:27 INFO MemoryStore: MemoryStore cleared
16/08/18 20:09:27 INFO BlockManager: BlockManager stopped
16/08/18 20:09:27 INFO BlockManagerMaster: BlockManagerMaster stopped
16/08/18 20:09:27 WARN MetricsSystem: Stopping a MetricsSystem that is not running
16/08/18 20:09:27 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
16/08/18 20:09:27 INFO Spark$SparkContext: Successfully stopped SparkContext
java.lang.IllegalArgumentException: requirement failed: File scala-parser-combinators_2.11-1.0.4.jar was already registered with a different path (old path = /home/spark2/.ammonium/bootstrap/scala-parser-combinators_2.11-1.0.4.jar, new path = /home/spark2/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar (requirement failed: File scala-parser-combinators_2.11-1.0.4.jar was already registered with a different path (old path = /home/spark2/.ammonium/bootstrap/scala-parser-combinators_2.11-1.0.4.jar, new path = /home/spark2/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar)
  scala.Predef$.require(Predef.scala:224)
  org.apache.spark.rpc.netty.NettyStreamManager.addJar(NettyStreamManager.scala:78)
  org.apache.spark.SparkContext.liftedTree2$1(SparkContext.scala:1703)
  org.apache.spark.SparkContext.addJar(SparkContext.scala:1702)
  org.apache.spark.SparkContext$$anonfun$11.apply(SparkContext.scala:457)
  org.apache.spark.SparkContext$$anonfun$11.apply(SparkContext.scala:457)
  scala.collection.immutable.List.foreach(List.scala:381)
  org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
  ammonite.Spark$SparkContext.<init>(Spark.scala:306)
  ammonite.Spark.sc(Spark.scala:226)
  cmd4$$user$$anonfun$1.apply(Main.scala:25)
  cmd4$$user$$anonfun$1.apply(Main.scala:24)
```

**Comment by maver1ck** [comment]
I think that problem starts with this patch:
https://github.com/apache/spark/pull/14396/files

But real bug is that we're trying to put same files twice.

**Comment by maver1ck** [comment]
I added back some exception handling.

I'm getting this:
java.lang.NoSuchMethodException: org.apache.spark.repl.ExecutorClassLoader.<init>(org.apache.spark.SparkConf, org.apache.spark.SparkEnv, java.lang.String, java.lang.ClassLoader, boolean)

Looks like we don't add spark jars do classpath. Why ?

**Comment by maver1ck** [comment]
I did the magic.
I use spark-submit to launch launcher as a kernel.

kernel.json

```
{
  "language" : "scala211",
  "display_name" : "Scala 2.11",
  "argv" : [
    "/mnt/mfs/spark-2.0/bin/spark-submit",
    "/home/spark2/.local/share/jupyter/kernels/scala211/launcher.jar",
    "-r",
    "file:/home/spark2/.m2/repository",
    "--quiet",
    "--connection-file",
    "{connection_file}"
  ]
}
```

Then:

```
classpath.add("com.github.alexarchambault.ammonium" % s"spark_2.0.1-SNAPSHOT_2.11.8" % "0.4.0-SNAPSHOT")
@transient val Spark = new ammonite.Spark
import Spark.{ sparkConf, sc, sqlContext }
sc.parallelize(Array(1,2,3,4)).map(x => x * 2).collect()
res5: Array[Int] = Array(2, 4, 6, 8)
```

**Comment by maver1ck** [comment]
Reopened because of 

```
java.lang.IllegalArgumentException: requirement failed: File scala-parser-combinators_2.11-1.0.4.jar was already registered with a different path (old path = /home/spark2/.ammonium/bootstrap/scala-parser-combinators_2.11-1.0.4.jar, new path = /home/spark2/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar
```

**Comment by bonitao** [comment]
Also hitting this. I load spark classes manually with interp.load.cp, but when I try to create the JupyterSparkSession, the addJar calls throw accusing of already having the same jar being loaded from a different path.

Maybe the code should catch the error and convert it into a warning? Or maybe make it possible for the user do first create the spark session and then add the jars, where he could choose to catch (or not) the exceptions himself?

I can cook a patch if you point out an acceptable solution.
