### ISSUE TITLE
java.lang.ClassNotFoundException when using predef.sc for initial SparkContext setup

### ISSUE THREAD

**Issue by ZeroHypotheses** [alexarchambault/ammonium#72]
Starting an ammonium REPL (using the `ammonium` command right from a fresh clone of this repo) and setting the SparkContext for a session works as expected:

```scala
Loading...
Welcome to the Ammonite Repl 0.8.1
(Scala 2.11.8 Java 1.8.0_71)
@ import $ivy.`org.slf4j:slf4j-nop:1.7.12` 
import $ivy.$                           
@ import $ivy.`org.apache.spark::spark-core:2.0.2` 
import $ivy.$                                   
@ import org.apache.spark.{SparkConf, SparkContext} 
import org.apache.spark.{SparkConf, SparkContext}
@ @transient val sparkConf = new SparkConf().setAppName("AmmoniumREPL").setMaster("local[*]") 

sparkConf: SparkConf = org.apache.spark.SparkConf@7785430c
@ @transient val sc = new SparkContext(sparkConf) 
@ val data = sc.parallelize(Seq(1,2,3)) 
data: org.apache.spark.rdd.RDD[Int] = ParallelCollectionRDD[3] at parallelize at cmd7.sc:1
@ data.map(_ + 1).foreach(println) 
2
3
4
```

However, when I put the imports and vals (`sparkConf`, `sc`) into a `~/.ammonite/predef.sc` so that I don't need to do that every time when starting a new REPL, I get the following exception:

```scala
Loading...
Compiling LoadedPredef.sc
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/rene/.coursier/cache/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.7.12/slf4j-nop-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/rene/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Welcome to the Ammonite Repl 0.8.1
(Scala 2.11.8 Java 1.8.0_71)
@ val data = sc.parallelize(Seq(1,2,3)) 
data: org.apache.spark.rdd.RDD[Int] = ParallelCollectionRDD[0] at parallelize at cmd0.sc:1
@ data.map(_ + 1).foreach(println) 
[Stage 0:>                                                          (0 + 0) / 2]org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.ClassNotFoundException: $sess.cmd1Wrapper$Helper$$anonfun$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
  org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
  scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
  org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
  scala.Option.foreach(Option.scala:257)
  org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
  org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
  org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:1886)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:1899)
  org.apache.spark.SparkContext.runJob(SparkContext.scala:1913)
  org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:894)
  org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:892)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
  org.apache.spark.rdd.RDD.foreach(RDD.scala:892)
  $sess.cmd1Wrapper$Helper.<init>(cmd1.sc:1)
  $sess.cmd1Wrapper.<init>(cmd1.sc:96)
  $sess.cmd1$.<init>(cmd1.sc:78)
  $sess.cmd1$.<clinit>(cmd1.sc:-1)
java.lang.ClassNotFoundException: $sess.cmd1Wrapper$Helper$$anonfun$1
  java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  java.lang.Class.forName0(Native Method)
  java.lang.Class.forName(Class.java:348)
  org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:67)
  java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
  java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
  java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
  java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
  java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
  java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
  java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
  org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
  org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
  org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
  org.apache.spark.scheduler.Task.run(Task.scala:86)
  org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)

@  
```

As already mentioned above, the content of my `~/.ammonite/predef.sc` looks as follows:

```scala
import $ivy.`org.slf4j:slf4j-nop:1.7.12`
import $ivy.`org.apache.spark::spark-core:2.0.2`
import org.apache.spark.{SparkConf, SparkContext}

@transient val sparkConf = new SparkConf().setAppName("AmmoniumREPL").setMaster("local[*]")
@transient val sc = new SparkContext(sparkConf)
```

Any ideas how I could fix that?

**Comment by alexarchambault** [comment]
If it's still an issue for you, try again with [ammonite-spark](https://github.com/alexarchambault/ammonite-spark) and the latest Ammonite.
